version: '3'

volumes:
  # We'll define a volume that will store the data from the postgres databases:
#  postgres-data:
#    driver: local
  # We'll define a volume that will store the data from the postgres databases:
  mysql-data:
    driver: local
  # The redis data store volume
  redis-data:
    driver: local

services:
  # Our PostgreSQL service:
  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: board
      MYSQL_USER: board
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD: board
#  pg:
#    image: postgres:10.5
#    ports:
#      # We'll bind our host's port 5432 to postgres's port 5432, so we can use
#      # our database IDEs with it:
#      - 5432:5432
#    volumes:
#      # We'll mount the 'postgres-data' volume into the location Postgres stores it's data:
#      - postgres-data:/var/lib/postgresql/data
#    environment:
#      POSTGRES_DB: discourse_development
#      POSTGRES_PASSWORD:

  # Our Redis service:
  redis:
    image: redis:4.0.8-alpine
    ports:
      # We'll bind our host's port 6379 to redis's port 6379, so we can use
      # Redis Desktop Manager (or other tools) with it:
      - 6379:6379
    volumes:
      # We'll mount the 'redis-data' volume into the location redis stores it's data:
      - redis-data:/var/lib/redis
    command: redis-server --appendonly yes
